version: '3.8'

services:
  fraud-detection-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./fraud_detection_model_final.pkl:/app/fraud_detection_model_final.pkl
    restart: unless-stopped
